import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, cpSync, readdirSync, statSync } from 'node:fs';
import { join, extname } from 'node:path';

const watch = process.argv.includes('--watch');
const DIST = 'dist';
mkdirSync(DIST, { recursive: true });

/** Inline every example .nib file into a module so the app ships self-contained. */
/** Deliberate order: the first one is what a visitor sees before they read a word. */
const ORDER = ['meridian', 'filings', 'sediment', 'orrery', 'tide', 'anemone', 'foxglove',
               'lattice', 'bloom', 'constellation', 'moire', 'ripple', 'static'];
function bundleExamples() {
  let files = [];
  try { files = readdirSync('examples').filter(f => f.endsWith('.nib')); } catch { }
  files.sort((a, b) => {
    const ia = ORDER.indexOf(a.replace(/\.nib$/, ''));
    const ib = ORDER.indexOf(b.replace(/\.nib$/, ''));
    return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
  });
  const out = files.map(f => {
    const src = readFileSync(join('examples', f), 'utf8');
    const first = src.split('\n').find(l => l.trim().startsWith('#')) ?? '';
    const m = /^#\s*(.+?)\s*(?:—|--|-)\s*(.+)$/.exec(first.replace(/^#\s*/, '# '));
    const title = m ? m[1].replace(/^#\s*/, '') : f.replace(/\.nib$/, '');
    const blurb = m ? m[2] : '';
    return { id: f.replace(/\.nib$/, ''), title, blurb, source: src };
  });
  writeFileSync('src/ide/examples.gen.ts',
    '// GENERATED by build.mjs — do not edit\n' +
    'export interface Example { id: string; title: string; blurb: string; source: string }\n' +
    'export const EXAMPLES: Example[] = ' + JSON.stringify(out, null, 2) + ';\n');
  return out.length;
}

const n = bundleExamples();

/** Copy www/* to dist, injecting the build stamp. */
function copyStatic() {
  for (const f of readdirSync('www')) {
    const p = join('www', f);
    if (statSync(p).isDirectory()) { cpSync(p, join(DIST, f), { recursive: true }); continue; }
    if (extname(f) === '.html') {
      let html = readFileSync(p, 'utf8');
      html = html.replace(/__BUILD__/g, new Date().toISOString().slice(0, 10));
      writeFileSync(join(DIST, f), html);
    } else cpSync(p, join(DIST, f));
  }
}

const opts = {
  entryPoints: { app: 'src/ide/app.ts' },
  bundle: true, format: 'esm', target: ['es2022'], platform: 'browser',
  outdir: DIST, sourcemap: true, minify: !watch, legalComments: 'none',
  logLevel: 'info',
};

/** Node-consumable library + CLI, for `npm test`, the CLI, and embedding. */
const libOpts = {
  bundle: true, format: 'esm', target: ['node18'], platform: 'node',
  outdir: DIST, sourcemap: false, logLevel: 'warning',
};
async function buildLib() {
  await esbuild.build({ ...libOpts, entryPoints: { nib: 'src/lang/nib.ts' } });
  await esbuild.build({ ...libOpts, entryPoints: { cli: 'src/cli/nib.ts' }});
}

if (watch) {
  const ctx = await esbuild.context(opts);
  await ctx.watch();
  await buildLib();
  copyStatic();
  console.log(`watching… (${n} examples)`);
} else {
  const r = await esbuild.build({ ...opts, metafile: true });
  await buildLib();
  copyStatic();
  const bytes = Object.values(r.metafile.outputs).filter(o => !o.entryPoint || true)
    .reduce((a, o) => a + o.bytes, 0);
  console.log(`built ${n} examples · ${(bytes / 1024).toFixed(1)} kB total`);
}
